language: node_js
node_js:
  - 7.7.1
notifications:
  email: false
  slack:
    secure: yO6sHaTfoMlhRSDoWkk/3ujs7tBtbsiKBmjtUa/WE4KoH1UMywxihQvNkYIg2FjRgtPRFMEBqnBh01jNcFOwQb/fgTSN/waEeNjEdN42lwZGWZRJ+9sUJFzAcS0+9o1XjCIZdzGZ4s7S4neB355l5ZPLDLI2gkHZ2FpyOPJgM075EwnIILLnQzJlYQWrh7snuxTb7I81RcyAh5ieT3RV/IoHZlrreejiLDzmYwK7VPBK9WFWOsxZ1MNco6XkkMTmvySR48aAK0YpXTTu5t3F4JrrIahpDcv8x8YiObf1Hw/Ft4rl9/759kE37wA3MBK/FVWIUXpcVzLtQEyIUuj5FAwmpExIhgwU8VD0/NOGdxvVQNt3Zu6c6d6yWfXT8IPlv6ZGae0vhJCskHfapHbXDT5L6Gl3u5L4Z2Ou66KhufTcr9D18x4aOa6CzlVWvPSSDr1F8tleM2i2rUfwwAQD9G49selPPulhaMBdUMwLGrQB4goKwHzqXzFvf6x1YOLLONSmBOJ+7U+n0kUuRbfrLDKWAh2ge2BP6TAEOA3D2aci8de9rQHaFK4XUuv6zg5r2qB1aFHKL/JLBoFnul64MlNKiO7vL208I2737EM+8zQi3Zz24CWvyW1IjjKuop3LuFuxKb5r2bifJosWLcUYVkxLfGI0nIzL3/1ZjApE7Q8=
