if: branch = master
language: node_js
node_js:
  - 8.15.0
notifications:
  email: false
  slack:
    secure: hKDYrlobpIeyElZRlM776NQ4jOnxmF94PYBUGDFq1QJNBRqNpSkOvZXmUo2jQDVhefFWcaMsD1XurGn5bB589ZgL0Z63L0yJWuAvTkYMm4aMb3Wa7jTkcLci5Uf004UYK9/QrX7nF65qgvDSsaQrS3TGKEYNdiFQS/xMAF6MLRjB53t0d3z01mdZlHR3p3t/XFxRL+bnOeJXvuLMF6UKjDdLzG9Y+5gbagtV7V8MEzLrYQE+M6aIo5fS6VOeGVjCkIZ5wz4V91dVUaIoeqGvu5msPA78QctMMBxDQlYg1OdG6pCXO1ZYVhbWCUO9A+nERSKysMlBEyd4mMwssk5A+ySt6Y2LiQH4nlXMvAMOs4vlE532obuziA29Ol8nBgDPZNKKrMbC1VqlMx5C/6egYCqpGKnO/AmBat21F+9Ukx+TDFiVlGGqK2UU9BFYJyYvkzwN95EgeT4nb0FqZMh6Bm380rKWch4f0b5slVuSo86oth1ojbf6EyFxfQpLMOw01qr7U7qqNucY6/VrzLPeQMA672vsaw/F5AA/Gh99Ha8x4YyxUJ9kzBnk9Qfb+1WIg8Rx1ss8qE7awzcW5HUb9h5iEFUlrkgZIZbWwRVL1kp794nAcvxcSP93l4CNRMOOrR4sSZlRbRfLI3eXxorO2GeMdNAtLp9Xmeh0qsY6wnE=
